language: objective-c
matrix:
    include:
        - osx_image: xcode9.3beta

script:
    - xcodebuild build test -project PolyKit.xcodeproj -scheme PolyKit -configuration Debug -destination "platform=iOS Simulator,name=iPhone X"

